name: Build Packages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-base-files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install makedeb
        run: |
          wget -qO - 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg 1> /dev/null
          echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
          sudo apt update
          sudo apt install makedeb
      
      - name: Build the package
        run: |
          cd base-files
          makedeb
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: base-files

          # todo: dont hardcode this
          path: base-files/base-files_11.1+deb11u5idnos1-1_amd64.deb
